on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install depedencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          message: "Automatically built unbuilt typescript"
          directories: ./
